apiVersion: v1
kind: Secret
metadata:
  name: phpmyadmin-secret
  namespace: dev
type: Opaque
data:
  PMA_USER: cm9vdA==           # base64 for "root"
  PMA_PASSWORD: cGFzc3dvcmQ=         # base64 of 'admin123'
