apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  namespace: dev
  labels:
    app: phpmyadmin
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - phpmyadmin
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1.5Gi"
          env:
            - name: PMA_HOST
              valueFrom:
                configMapKeyRef:
                  name: phpmyadmin-config
                  key: PMA_HOST
            - name: PMA_PORT
              valueFrom:
                configMapKeyRef:
                  name: phpmyadmin-config
                  key: PMA_PORT
            - name: TRUST_PROXY_HEADERS     # üîÅ AJOUT√â pour HTTPS via Ingress
              value: "1"
            - name: PMA_ABSOLUTE_URI
              value: https://phpmyadmin.dev.local/
#            - name: PMA_USER
#              valueFrom:
#                secretKeyRef:
#                  name: mariadb-secret
#                  key: MARIADB_ROOT_USER
#            - name: PMA_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: mariadb-secret
#                  key: MARIADB_ROOT_PASSWORD
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30092
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: phpmyadmin-hpa           # Nom du HPA
  namespace: dev               # Namespace o√π le HPA est cr√©√© (ici "dev")
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: phpmyadmin-deployment  # Le d√©ploiement cible que le HPA va surveiller et scaler
  minReplicas: 2               # Nombre minimum de pods que Kubernetes doit garder actifs
  maxReplicas: 4               # Nombre maximum de pods que Kubernetes peut cr√©er automatiquement
  metrics:                     # Crit√®res utilis√©s pour d√©cider de scaler
    - type: Resource           # Le premier crit√®re est une ressource
      resource:
        name: cpu              # Cette ressource est le CPU (processeur)
        target:
          type: Utilization    # Le HPA surveille l‚Äôutilisation (en pourcentage)
          averageUtilization: 80 # Si l‚Äôutilisation moyenne de CPU d√©passe 80%, Kubernetes cr√©e plus de pods
    - type: Resource           # Deuxi√®me crit√®re √©galement une ressource
      resource:
        name: memory           # Cette ressource est la m√©moire (RAM)
        target:
          type: Utilization    # Surveille aussi l‚Äôutilisation m√©moire
          averageUtilization: 80 # Si la m√©moire utilis√©e d√©passe 80%, Kubernetes augmente aussi les pods
